apiVersion: v1
kind: Namespace
metadata:
  name: hotelup-payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelup-payment-deployment
  labels:
    app: hotelup-payment
  namespace: hotelup-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotelup-payment
  template:
    metadata:
      name: hotelup-payment
      labels:
        app: hotelup-payment
    spec:
      containers:
        - name: hotelup-payment
          image: wiaz/hotelup.payment:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5007
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hotelup-payment-service
  labels:
    app: hotelup-payment
  namespace: hotelup-payment
spec:
    selector:
        app: hotelup-payment
    ports:
        - protocol: TCP
          port: 5007
          targetPort: 5007
    type: LoadBalancer
      